import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from './config/material-tailwind-theme-provider';
import ReactQueryClientProvider from './config/ReactQueryClientProvider';

export const metadata: Metadata = {
  title: 'supa-todo',
  description: 'Generated by create next app',
};

//recoilprovider 감싸기는 body 기준입니다.
//react-querty provider 감싸기는 body 기준입니다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="ko">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
            integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <ReactQueryClientProvider>
          <body>{children}</body>
        </ReactQueryClientProvider>
      </html>
    </ThemeProvider>
  );
}
