import type { Metadata } from 'next';
import './globals.css';
import RecoilProvider from './config/RecoilProvider';
import ReactQueryProvider from './config/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'supa-todo',
  description: 'Generated by create next app',
};
//recoilprovider 감싸기는 body 기준입니다.
//react-querty provider 감싸기는 body 기준입니다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <RecoilProvider>{children}</RecoilProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
